version: '3'

services:
  backend_example:
    image: 'backend_example'
    ports:
      - 8000:8000
    environment:
      - REDIS=redis_store
      - REDIS_PORT=6379

  frontend_example:
    image: 'frontend_example'
    ports:
      - 5000:5000
  
  redis_store:
    image: 'redis'
