version: '3.5'

services:

  frontend:
    image: frontend_example
    ports:
      - 5000:5000

  backend:
    image: backend_example
    environment:
      - DB_USERNAME=tree
      - DB_PASSWORD=password
      - DB_NAME=tree
      - DB_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=tree
    container_name: postgres_db
    volumes:
      - postgres_database:/var/lib/postgresql/data

volumes:
  postgres_database:
