FROM ubuntu:16.04

ENV FRONT_URL=http://localhost:5000
EXPOSE 8000

WORKDIR /backend
COPY . .

RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs && \ 
    npm install && \
    apt-get purge -y --auto-remove curl python2.7 python3.5 libexpat1 libmagic1 mime-support && \
    rm -rf /var/lib/apt/lists/* && \
    useradd -m backend_app && chown -R backend_app: /backend

USER backend_app

CMD ["npm", "start"]
